[app]
name = "logseq"
description = "Logseq - Privacy-first Knowledge Base"
homepage = "https://logseq.com/"

[source]
type = "appimage"
url = "https://github.com/logseq/logseq/releases/latest/download/Logseq-linux-x64.AppImage"
architecture = ["x86_64"]

[metadata]
categories = ["Office", "NoteTaking"]
desktop_entry = true
