[app]
name = "nvim"
description = "Neovim - Hyperextensible Vim-based text editor"
homepage = "https://neovim.io/"

[source]
type = "appimage"
url = "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage"
architecture = ["x86_64"]

[metadata]
categories = ["Development", "TextEditor"]
desktop_entry = false
